# Make calls to the web APIs through VScode and the plugin REST Client.
# To install the plugin see the Marketplace link https://marketplace.visualstudio.com/items?itemName=humao.rest-client

### Home route
GET http://localhost:3001/

### Signup route
POST http://localhost:3001/auth/register
Content-Type: application/json

{
    "email" : "houssem@example.com",
    "firstName" : "first name",
    "lastName" : "last name",
    "password" : "123456",
    "confirmPassword": "123456"
}

### SignIn
POST http://localhost:3001/auth/login
Content-Type: application/json

{
    "email" : "houssem@example.com",
    "password" : "123456"
}

### Get /me  get current connected user
GET http://localhost:3001/auth/me


### Logout
GET http://localhost:3001/auth/logout

### Get interview levels
GET http://localhost:3001/interviews/difficulty-levels

### Create new interview
POST  http://localhost:3001/interviews
Content-Type: application/json

{
    "level" : "5f48e2a54552ce3c08d538ca",
    "title" : "Time Convertion"
}

### Get list of interviews for the connected user
GET  http://localhost:3001/interviews

### Join an interview
GET  http://localhost:3001/interviews/-0tIX4wSLk/join

### Exit interview room
GET  http://localhost:3001/interviews/-0tIX4wSLk/exit